
# Conclusion

In this work, we presented Bayesian Optimization (BO) workflow for robust production optimization. First, a 1-D problem case was considered to illustrate the workflow better and explain the workflow's detail. Then, the workflow was tested for production optimization of the 3-D synthetic reservoir model.

We conclude that the BO has a high potential for the problem where the objective function is expensive to evaluate. This is often the case in production optimization, where a hundred(s) of geological realizations represent uncertainty in the objective function. Compared with other commonly used methods like PSO or GA, BO tries to build a probabilistic model of objective function. This probabilistic model is used to think strategically and pick the next point for evaluation sequentially. Utilizing the probabilistic model and having a consistent policy to select the next point leads BO to need expensive forward evaluation a few times less than GA and PSO.

In this work, the main goal was to provide evidence of the applicability of BO for robust optimization. The field cases problem considered was a relatively medium dimension size. However, given the potential benefits of workflow presented in this work, we would like to encourage researchers to apply the BO to the high-dimensional optimization problem. Future work could explore the use of BO for joint optimization of well location and well control. The joint problem will naturally lead to a high-dimensional problem. It would be helpful to see BO performance when there are some inequality constraints (typical in placement problems) as well. Finally, on the theory side, the BO with a non-myopic policy in sequential data gathering will also lead to more efficiency in the performance of BO is worth having a look at.

\newpage

# Acknowledgements {#ack .unnumbered}

This work received support from the Research Council of Norway and the companies AkerBP, Wintershall--DEA, Vår Energy, Petrobras, Equinor, Lundin, and Neptune Energy, through the Petromaks--2 DIGIRES project (280473) (<http://digires.no>).

# Note on Reproducibility of Research {#rep .unnumbered}

The code, data, and executable link of this manuscript are available to reproduce this paper. The paper has been written in Rmarkdown format [@xie2018], and the reader can find all elements in the Github repo: (<https://github.com/Peymankor/Bayesopt_well_control>). However, the repo will stay "private," We will change its access to "public" as soon as the manuscript is accepted for publication.

\newpage

# Glossary {#glossary .unnumbered}

**Nomenclature**

-   $p$

Price in $dollar/m^3$

-   $q$

Volume in $m^3/D$

-   $N_p$

Number of production wells

-   $N_{wi}$

Number of injection wells

-   $\mathbf{u}$

Control variable (decision to make)

-   $\mathbf{U}$

Vector of control variables

-   $m$

Mean function

$k$

Covariance function

**Greek Symbols**

-   $\mathcal{MN}$

Multivariate normal distribution

-   $\mathcal{N}$

Normal distribution

-   $\mu$

Mean of normal distribution

-   $\theta$

Parameter of covariance function

-   $\sigma$

Standard deviation of normal distribution

-   $\alpha_{EI}$

utility function when policy is Expected Improvement

-   $\Phi$

CDF of standard Gaussian distribution

-   $\phi$

PDF of standard Gaussian distribution

-   $\epsilon$

Explorative term

**Subscription**

-   $o$

Oil

-   $wp$

Produced Water

-   $wi$

Injection Water

-   $EI$

Expected Improvement

\newpage

# Appendix I {#app1 .unnumbered}

Here, we first start to derive the case when mean function $m(\mathbf{u})$ is considered as equal to zero, $m(\mathbf{u})=0$. Then, we generalize the resulting equations to the case of fixed, deterministic mean function.

Now, we can write analytical term of multivariate gaussian distribution for both $\mathcal{N}_{n+1}$, $\mathcal{N}_{n}$:

```{=tex}
\begin{align}
  \begin{split}
p(\mathbf{J_{u_*}}|\mathbf{J_{U}})= & \:\frac{\mathcal{N}_{n+1}\begin{pmatrix}
\begin{bmatrix}
\mathbf{J_{u_*}} \\ \mathbf{J_{U}}  
\end{bmatrix} \Bigg|
0,\begin{bmatrix} \mathbf{\kappa}_{u_\ast,u_\ast} &  \mathbf{K}_{U,u_\ast} \\
\mathbf{K}^\intercal_{U,u_\ast} & \mathbf{K}_{U,U}
\end{bmatrix} \\
\end{pmatrix}}{\mathcal{N}_{n}\begin{pmatrix}\mathbf{J_{U}}\Bigg|
0, \mathbf{K}_{U,U} \\
\end{pmatrix}} \\
& \:\propto \exp 
\begin{pmatrix} -\frac{1}{2} 
\begin{bmatrix}\mathbf{J_{u_*}} & \mathbf{J_{U}}
\end{bmatrix}
\begin{bmatrix}\mathbf{\kappa}_{u_\ast,u_\ast} &  \mathbf{K}_{U,u_\ast} \\
\mathbf{K}^\intercal_{U,u_\ast} & \mathbf{K}_{U,U} 
\end{bmatrix}^{-1}\begin{bmatrix}\mathbf{J_{u_*}} \\ \mathbf{J_{U}}\end{bmatrix}
-\mathbf{J_{U}^\intercal}\mathbf{K}_{U,U}^{-1}\mathbf{J_{U}}\end{pmatrix} \\
& \:  
  \end{split}
\label{eq:mix-equ-app}
\end{align}
```

Here, we substitute the inverse of covariance of matrix with following matrix:

```{=tex}
\begin{equation}
\begin{bmatrix}d &  b \\
b^\intercal & A 
\end{bmatrix}=\begin{bmatrix}\mathbf{\kappa}_{u_\ast,u_\ast} &  \mathbf{K}_{U,u_\ast} \\
\mathbf{K}^\intercal_{U,u_\ast} & \mathbf{K}_{U,U} 
\end{bmatrix}^{-1}
\label{eq:substitute}
\end{equation}
```
We can multiply term inside the exponential term:

```{=tex}
\begin{align}
  \begin{split}
p(\mathbf{J_{u_*}}|\mathbf{J_{U}}) & \propto \exp 
\begin{pmatrix} -\frac{1}{2} 
\begin{bmatrix}\mathbf{J_{u_*}} & \mathbf{J_{U}}
\end{bmatrix}
\begin{bmatrix}d &  b \\
b^\intercal & A \end{bmatrix}\begin{bmatrix}\mathbf{J_{u_*}} \\ \mathbf{J_{U}}\end{bmatrix}
+\mathbf{J_{U}^\intercal}\mathbf{K}_{U,U}^{-1}\mathbf{J_{U}}\end{pmatrix} \: \\
& \:\propto \exp \begin{pmatrix} -\frac{1}{2} 
\begin{bmatrix}(\mathbf{J_{u_*}}d+\mathbf{J_{U}}b^\intercal)\mathbf{J_{u_*}} +(\mathbf{J_{u_*}}b+\mathbf{J_{U}}A)\mathbf{J_{U}} 
\end{bmatrix}
\end{pmatrix}
 \\
& \:  
  \end{split}
\label{eq:exp-term-app}
\end{align}
```

Now, we will multiply only the terms that is related to $\mathbf{J_{u_*}}$ (inside the exponential term), as that is the variable of interest, rest of term was replaced by "const" term. Taking the $d$ value out of the bracket term, now we can find :

```{=tex}
\begin{equation}
\exp 
\begin{pmatrix} -\frac{1}{2} 
\begin{bmatrix}d(\mathbf{J_{u_*}})^2+2b^\intercal\mathbf{J_{U}}\mathbf{J_{u_*}}+const
\end{bmatrix}
\end{pmatrix}\propto \exp 
\begin{pmatrix} -\frac{1}{2d^{-1}} 
\begin{bmatrix}\mathbf{J_{u_*}}+\frac{b^\intercal\mathbf{J_{U}}}{d}
\end{bmatrix}^2
\end{pmatrix}
\label{eq:mix-equ-app3}
\end{equation}
```

Where the resulting equation is proportional to normal density function, with mean and variance can be defined as:

```{=tex}
\begin{align}
  \begin{split}
p(\mathbf{J_{u_*}}|\mathbf{J_{U}},\theta^\ast)= & \:  \mathcal{N}_{1}(\mathbf{J_{u_*}}| \mathbf{\mu_{u_\ast}}, \mathbf{\sigma^2_{u_{\ast}}}) \\
\mathbf{\mu_{u_\ast}}= & \:\frac{b^\intercal\mathbf{J_{U}}}{d} \\
\textstyle \sigma^2_{\mathbf{u_{\ast}}}=& \:d^{-1}
  \end{split}
\label{eq:post-mean-cov-single-zero-orig}
\end{align}
```

However, we should say that in the above equation still $d$ and $b^\intercal$ are undefined. Now, we find the analytical expression for those terms. 

Per definition of matrix and it's inverse:

```{=tex}
\begin{equation}
\begin{bmatrix}\mathbf{\kappa}_{u_\ast,u_\ast} &  \mathbf{K}_{U,u_\ast} \\
\mathbf{K}^\intercal_{U,u_\ast} & \mathbf{K}_{U,U} 
\end{bmatrix}\begin{bmatrix}d &  b \\
b^\intercal & A 
\end{bmatrix}=\begin{bmatrix}1 &  0 \\
0 & \mathbf{I} 
\end{bmatrix}
\label{eq:inv-def}
\end{equation}
```

And then, writing element-by-element equivalent equations:

```{=tex}
\begin{subequations}
 \begin{align}
  \label{eq:eq1}
  \mathbf{\kappa}_{u_\ast,u_\ast}d+\mathbf{K}_{U,u_\ast}b^\intercal=1\\
  \label{eq:eq2}
  \mathbf{\kappa}_{u_\ast,u_\ast}b+\mathbf{K}_{U,u_\ast}A=0\\
  \label{eq:eq3}
  \mathbf{K}^\intercal_{U,u_\ast}d+\mathbf{K}_{U,U}b^\intercal=0\\
  \label{eq:eq4}
  \mathbf{K}^\intercal_{U,u_\ast}b+\mathbf{K}_{U,U}A=\mathbf{I}
 \end{align}
\label{eq:main1}
\end{subequations}
```

We can find the $b^\intercal$ through Equation \@ref(eq:eq3)

```{=tex}
\begin{equation}
b^\intercal=-\frac{\mathbf{K}^\intercal_{U,u_\ast}d}{\mathbf{K}_{U,U}}
\label{eq:find-bt}
\end{equation}
```

Replacing the $b^\intercal$ in Equation  \@ref(eq:eq1) we can define the $d$ as:

```{=tex}
\begin{align}
\begin{aligned}
\mathbf{\kappa}_{u_\ast,u_\ast}d-\mathbf{K}^\intercal_{U,u_\ast}\mathbf{K}_{U,U}^{-1}\mathbf{K}_{U,u_\ast}d=1 \\
d=\frac{1}{\mathbf{\kappa}_{u_\ast,u_\ast}-\mathbf{K}^\intercal_{U,u_\ast}\mathbf{K}_{U,U}^{-1}\mathbf{K}_{U,u_\ast}}
\label{eq:find-d}
\end{aligned}
\end{align}
```
Then, Equation \@ref(eq:post-mean-cov-single-zero-orig) can be defined with equivalent term of $b^\intercal$ and $d$:

```{=tex}
\begin{align}
  \begin{split}
p(\mathbf{J_{u_*}}|\mathbf{J_{U}},\theta^\ast)= & \:  \mathcal{N}_{1}(\mathbf{J_{u_*}}| \mathbf{\mu_{u_\ast}}, \mathbf{\sigma^2_{u_{\ast}}}) \\
\mathbf{\mu_{u_\ast}}= & \:\frac{b^\intercal\mathbf{J_{U}}}{d}= \mathbf{K}^\intercal_{U,u_\ast}{\mathbf{K}^{-1}_{U,U}}\mathbf{J_{U}} \\
\textstyle \sigma^2_{\mathbf{u_{\ast}}}=& \:d^{-1}=  \normalsize{\mathbf{\kappa}_{u_\ast,u_\ast}-\mathbf{K}^\intercal_{U,u_\ast}\mathbf{K}_{U,U}^{-1}\mathbf{K}_{U,u_\ast}}
  \end{split}
\label{eq:post-mean-cov-single-zero-proof}
\end{align}
```

In the case of using a fixed (deterministic) mean function $m(\mathbf{u})$, we simply apply the above zero mean GP to the difference between the observations and the fixed mean function, where equation for variance keeps unchanged:

```{=tex}
\begin{align}
  \begin{split}
p(\mathbf{J_{u_*}}|\mathbf{J_{U}},\theta^\ast)= & \:  \mathcal{N}_{1}(\mathbf{J_{u_*}}| \mathbf{\mu_{u_\ast}}, \mathbf{\sigma^2_{u_{\ast}}}) \\
\mathbf{\mu_{u_\ast}}= & \:  m(\mathbf{u_\ast}) +\mathbf{K}^\intercal_{U,u_*} \mathbf{K}^{-1}_{U,U}(\mathbf{J_U}-m(\mathbf{U})) \\
\textstyle \sigma^2_{\mathbf{u_{\ast}}}=& \:  \normalsize{\mathbf{\kappa}_{u_\ast,u_\ast}-\mathbf{K}^\intercal_{U,u_\ast}\mathbf{K}_{U,U}^{-1}\mathbf{K}_{U,u_\ast}}
  \end{split}
\label{eq:post-mean-cov-single-app}
\end{align}
```
Which is identical to Equation \@ref(eq:post-mean-cov-single).

\newpage

# References {#references .unnumbered}
